export const BLOG_POSTS = [
  {
    slug: 'engine-warning-light-guide',
    title: 'Engine Warning Light: What It Means & What To Do',
    excerpt: 'Understanding your engine warning light can save you hundreds. Learn what different warning lights mean, common causes, and when you need immediate help.',
    category: 'diagnostics',
    date: 'November 20, 2025',
    readTime: '8 min read',
    author: 'FixNow Mechanics'
  },
  {
    slug: 'mobile-mechanic-vs-garage',
    title: 'Mobile Mechanic vs Traditional Garage: Cost Comparison',
    excerpt: 'Discover why mobile mechanics can save you 30-60% on common repairs. We break down the real costs including recovery, labour rates, and hidden fees most people forget.',
    category: 'costs',
    date: 'November 18, 2025',
    readTime: '10 min read',
    author: 'FixNow Mechanics'
  },
  {
    slug: 'brake-warning-signs',
    title: '5 Warning Signs Your Brakes Need Immediate Attention',
    excerpt: 'Squeaking, grinding, or soft pedals? Learn the critical warning signs that mean your brakes need urgent repairs.',
    category: 'Brakes',
    date: 'Nov 15, 2025',
    readTime: '7 min read',
    icon: '🛑',
    author: 'FixNow Mechanics',
  },
  {
    slug: 'car-battery-lifespan',
    title: 'How Long Should a Car Battery Last? (And How to Extend It)',
    excerpt: 'Understanding car battery lifespan, warning signs of failure, and practical tips to get more years from your battery.',
    category: 'Maintenance',
    date: 'Nov 12, 2025',
    readTime: '9 min read',
    icon: '🔋',
    author: 'FixNow Mechanics',
  },
  {
    slug: 'service-intervals-explained',
    title: 'Car Service Intervals Explained: Full vs Interim Service',
    excerpt: 'What\'s the difference between a full service and interim service? When do you need each, and what\'s actually checked?',
    category: 'Maintenance',
    date: 'Nov 10, 2025',
    readTime: '10 min read',
    icon: '🔧',
    author: 'FixNow Mechanics',
  },
  {
    slug: 'winter-car-preparation',
    title: 'Winter Car Preparation: Essential Checks Before Cold Weather',
    excerpt: 'Get your car ready for winter with these essential checks. Prevent breakdowns and stay safe in cold weather.',
    category: 'Seasonal',
    date: 'Nov 8, 2025',
    readTime: '8 min read',
    icon: '❄️',
    author: 'FixNow Mechanics',
  },
  {
    slug: 'engine-light-diagnosis',
    title: 'Engine Management Light On? Here\'s What to Do',
    excerpt: 'Step-by-step guide on what to do when your engine light comes on, from immediate checks to professional diagnostics.',
    category: 'Diagnostics',
    date: 'Nov 5, 2025',
    readTime: '7 min read',
    icon: '⚠️',
    author: 'FixNow Mechanics',
  },
  {
    slug: 'suspension-noise-guide',
    title: 'Car Making Clunking Noises? Suspension Problems Explained',
    excerpt: 'Identify common suspension noises, what causes them, and whether they\'re safe to drive with.',
    category: 'Repairs',
    date: 'Nov 3, 2025',
    readTime: '9 min read',
    icon: '🔊',
    author: 'FixNow Mechanics',
  },
  {
    slug: 'pre-purchase-inspection',
    title: 'Buying a Used Car? Why You Need a Pre-Purchase Inspection',
    excerpt: 'Protect your investment with a professional pre-purchase inspection. What we check and how it saves you thousands.',
    category: 'Advice',
    date: 'Nov 1, 2025',
    readTime: '8 min read',
    icon: '🔍',
    author: 'FixNow Mechanics',
  },
];

export function getBlogPostBySlug(slug) {
  return BLOG_POSTS.find(post => post.slug === slug);
}
